//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUsers
    {
        public int id { get; set; }
        public string siteuser { get; set; }
        public string siterole { get; set; }
        public string password { get; set; }
    }
}
