//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkpoint4Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.Sells = new HashSet<Sells>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Sells> Sells { get; set; }
    }
}
