//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkpoint4Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sells
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int client { get; set; }
        public int good { get; set; }
        public double sum { get; set; }
        public int manager { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual Managers Managers { get; set; }
    }
}
